### PR TITLE
Render text

### PR DESCRIPTION
**Pull request by sdhull**
Slight refactor + adds `#render_text` methods to the version renderers & renderer wrapper

### CODE REVIEW

**Comment by nolman** [comment]
For plain text emails?

**Comment by nolman** [comment]
If this is for plaintext emails it's not quite right as links won't go through in plaintext.

**Comment by sdhull** [comment]
For subject & to in emails

**Comment by sdhull** [comment]
Plain text emails will be html => markdown, not plain text

**Pull request merged**
